name: Hexo Blog CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: 1. 检查master分支
        uses: actions/checkout@master

      - name: 2. 设置Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: 3. 缓存
        uses: actions/cache@v2
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/yarn.lock')}}

      - name: 4. 安装插件
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          export TZ='Asia/Shanghai'
          yarn install
      - name: 6. 部署页面
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: master
          folder: public
          repository-name: BilShiziheng/stoneblogwithazy
          clean: false
          ssh-key: ${{ secrets.DEPLOY_KEY }}
