name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Hexo自动部署流水线.
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true # Checkout private submodules(themes or something else).

    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.)
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12' #超过12的版本有几个warning，我不想处理

    # Deploy hexo blog website.
    - name: 安装 Hexo
      env:
        # 定义了一个变量 secrets里面添加的名字
        ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
      run: |
          # 创建了一个ssh文件夹
          mkdir -p ~/.ssh/
          # 把key复制进去
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # 配置git
          git config user.email "shizihenh@163.com"  
          git config user.name "BilShiziheng"
          # 安装hexo
          npm install hexo-cli -g
          npm install

    - name: 部署ing
      run: |
        hexo clean
        hexo deploy
